use bon::bon;

use crate::hall_symbols::translation_symbol::TranslationSymbol;

use super::{
    notations::{NFold, NFoldDiag, NFoldSub, RotationAxis},
    MatrixSymbol, MatrixSymbolError,
};

/// Fallible, cross-field-validating constructor, generated by `bon`.
///
/// Entry point: `MatrixSymbol::new()` returns the `NewBuilder` typestate
/// builder. Omitting `nfold_body` is a compile error. `build()` returns
/// `Result<MatrixSymbol, MatrixSymbolError>` and enforces the rules that
/// `get_rotation_matrix` (fold / diag / axis) and `set_transform`
/// (fold / sub) already encode. This file does not duplicate that table;
/// the constructor calls into both functions on the candidate symbol.
///
/// Enforced rules:
///
/// - `NFold::N2`, `N3`, `N4`, `N6` need an explicit rotation axis.
///   `RotationAxis::Omitted` is invalid. `NFold::N1` accepts any axis.
/// - `NFold::N2` plus `NFoldDiag::Asterisk` is invalid.
/// - `NFold::N3` allows `NFoldDiag::None` or `Asterisk` only.
///   The quote forms are invalid.
/// - `NFold::N4` and `NFold::N6` allow `NFoldDiag::None` only.
/// - Sub-numbers: `N3` allows `None, N1, N2`; `N4` allows
///   `None, N1, N3`; `N6` allows `None, N1, N2, N4, N5`.
#[bon]
impl MatrixSymbol {
    // The generated start function `new()` returns the builder, not
    // `Self`. This is the expected shape of a bon builder entry point.
    /// The cross-field-validating constructor, fallible.
    ///
    /// The generated `new()` entry returns the `NewBuilder`. Its
    /// `build()` returns `Result<MatrixSymbol, MatrixSymbolError>` and
    /// runs the rules that `get_rotation_matrix` and `set_transform`
    /// already encode. This function does not duplicate that table.
    #[allow(clippy::new_ret_no_self)]
    #[builder(start_fn = new, builder_type = NewBuilder, finish_fn = build)]
    pub fn from_parts(
        #[builder(default)] minus_sign: bool,
        nfold_body: NFold,
        #[builder(default)] nfold_sub: NFoldSub,
        #[builder(default)] nfold_diag: NFoldDiag,
        #[builder(default)] rotation_axis: RotationAxis,
        translation_symbols: Option<Vec<TranslationSymbol>>,
    ) -> Result<MatrixSymbol, MatrixSymbolError> {
        let symbol = MatrixSymbol {
            minus_sign,
            nfold_body,
            nfold_sub,
            nfold_diag,
            rotation_axis,
            translation_symbols,
        };
        let rot_mat = symbol.get_rotation_matrix()?;
        symbol.set_transform(rot_mat)?;
        Ok(symbol)
    }
}
